### ISSUE TITLE
Suggestions suite au live twitch 

### ISSUE THREAD

**Issue by zendrique** [blue-keys/HistoryLive#1]
Bonjour,
Je ne sais pas trop ci c'est le bon endroit car "ouvrir un ticket" sur un repos GitHub c'est un peu particulier... Bref. 

Je fais suite à votre live Twitch pour vous signaler mes quelques suggestions et point à améliorer :
 
- Dans un premier temps, je trouve dommage qu’il n'y a pas eu de présentation des team (de ce qu'elle faisait, de la communauté....). 

- Ensuite les voie étaient inégal sur le point de vue du son, certaines étaient très bien, d'autres trop fortes, et d'autres pas assez fortes.

Voilà voilà 🙄

**Comment by leolios** [comment]
@zendrique salut, merci pour tes retours, nous venons de remettre en ligne un outil meilleur pour les suggestions et avons ajouter dans la liste ce que tu as indiqué. N'hésite pas à suivre l'évolution avec les notifications :+1: 

[https://suggestion.bluekeys.org/historylive](https://suggestion.bluekeys.org/historylive)
